### ISSUE TITLE
Writing multiple user info in same file instead of creating new file each time

### ISSUE THREAD

**Issue by wenwei1234** [Moesha1905/User_ApplicationForm#1]
https://github.com/Moesha1905/User_ApplicationForm/blob/1dabd62953111ff6e17465b1dbdb3e3bcdff45a8/my-new-app/src/Components/Confirm.js#L14

**Comment by Moesha1905** [comment]
Removed excel sheet generation since storing locally to the system didn't allow appending data but regenerating a new excel sheet with appended data. 

Integrated API for google sheet to store all the data.
