### ISSUE TITLE
Combine FormUserDetails and FormPersonalDetails into a Single Component

### ISSUE THREAD

**Issue by mithraan17** [Moesha1905/User_ApplicationForm#6]
FormUserDetails and FormPersonalDetails are separate components for gathering user input in two different steps. This leads to redundant code and increases maintenance complexity.

We need to combine both of these forms into a single component while maintaining the functionality of a multi-step form. The first form should collect the user details (first name, last name, and email), and the second form should collect the personal details (occupation, city, and bio).

**Comment by Moesha1905** [comment]
The implementation was tried and I had noticed that, making these changes could significantly impact the functionality and user experience of the multi-step form. Keeping the steps modular, as they are now, ensures the code is easier to manage and maintain. Removing navigation functions like `nextStep` and `prevStep` would make it harder for users to move through the form or go back to make changes, which could be frustrating. Without these, it would be harder to validate inputs, retain user progress, and prepopulate fields when needed. So, I believe that the current approach is designed to provide a smoother user experience and a more maintainable codebase. 

If there is any other recommendations that I could look into, please feel free to let me know :)
